language: php
php:
    - 5.5
    - 5.6
    - nightly

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install
    
before_script:
    - php vendor/codeception/codeception/codecept build

script: php vendor/codeception/codeception/codecept run

